### ISSUE TITLE
Hackage Release 

### ISSUE THREAD

**Issue by fendor** [Bodigrim/cabal-add#7]
Since https://github.com/haskell/haskell-language-server/pull/4360 adds a CodeAction which utilises `cabal-add` to add a dependency to a `.cabal` file, it would be much easier for HLS (especially when HLS does a Hackage release) if `cabal-add` was released to Hackage as well.

While we are not releasing right now, this issue aims to track a potential Hackage release.

cc @VenInf

**Comment by Bodigrim** [comment]
Sure, I'm happy to release once https://github.com/haskell/haskell-language-server/pull/4360 is merged.

**Comment by fendor** [comment]
@Bodigrim The PR has been merged :confetti_ball:

**Comment by Bodigrim** [comment]
Done, https://hackage.haskell.org/package/cabal-add-0.1.
